export const getStoreMediaCopy = (language = "en") => {
  const isTurkish = String(language || "").toLowerCase().startsWith("tr");

  return isTurkish
    ? {
        storeStories: "Mağaza Hikâyeleri",
        storyLoading: "Mağaza hikâyeleri yükleniyor",
        watchStory: "Hikâyeyi izle",
        watchVideo: "Videoyu izle",
        video: "Video",
        watchOnYouTube: "YouTube'da izle",
        watchOnTikTok: "TikTok'ta izle",
        visitStore: "Mağazayı ziyaret et",
        close: "Kapat",
        previous: "Önceki",
        next: "Sonraki",
        storeHighlights: "Mağaza öne çıkanları",
        storeVideos: "Mağaza Videoları",
        videosButton: "Videolar",
        highlightDescription: "Mağazanın kalıcı video vitrini.",
        mediaLoading: "Mağaza medyası yükleniyor",
        addMedia: "Medya ekle",
        storeMedia: "Mağaza medyası",
        sellerIntro:
          "Herkese açık YouTube veya TikTok video bağlantınızı yapıştırın. Shopera bunu Mağaza Hikâyesi veya Mağaza Videosu olarak gösterir; alıcı arayüzünde platform etiketi gösterilmez.",
        title: "Başlık",
        titlePlaceholder: "Örn. Yaz koleksiyonumuz",
        videoUrl: "Video bağlantısı",
        videoUrlPlaceholder: "YouTube veya TikTok bağlantısını yapıştırın",
        detected: "Algılandı",
        invalidVideoUrl: "Geçerli bir HTTPS YouTube veya TikTok bağlantısı yapıştırın.",
        homeStory: "Ana sayfa hikâyesi",
        homeStoryHint: "24 saat görünür · mağaza başına en fazla 2 aktif hikâye",
        storeShowcase: "Mağaza vitrini",
        storeShowcaseHint: "Mağaza sayfasında siz kaldırana kadar kalır",
        publish: "Yayınla",
        publishing: "Yayınlanıyor...",
        activeStories: "Aktif ana sayfa hikâyeleri",
        permanentShowcase: "Kalıcı mağaza vitrini",
        noStories: "Henüz aktif ana sayfa hikâyesi yok.",
        noShowcase: "Henüz kalıcı vitrin videosu yok.",
        noStoriesPublic: "Şu anda yayında mağaza hikâyesi yok.",
        noStoriesPublicHint: "Shopera mağazalarının yeni hikâyeleri burada görünecek.",
        noShowcasePublic: "Henüz mağaza öne çıkanı yok.",
        noShowcasePublicHint: "Bu mağaza henüz bir video eklemedi.",
        storiesUnavailable: "Mağaza Hikâyeleri şu anda kullanılamıyor.",
        showcaseUnavailable: "Mağaza öne çıkanları şu anda kullanılamıyor.",
        tryAgainLater: "Lütfen biraz sonra tekrar deneyin.",
        comingSoon: "Yakında",
        remove: "Kaldır",
        removeConfirm: "Bu medyayı kaldırmak istiyor musunuz?",
        yesRemove: "Evet, kaldır",
        cancel: "Vazgeç",
        expired: "Süresi doldu",
        hoursLeft: "{{hours}} sa kaldı",
        minutesLeft: "{{minutes}} dk kaldı",
        permanent: "Kalıcı",
        homeLimit: "2 aktif hikâye sınırı",
        loadError: "Mağaza medyası yüklenemedi.",
        publishError: "Medya yayınlanamadı.",
        removeError: "Medya kaldırılamadı.",
        retry: "Tekrar dene",
        youtube: "YouTube",
        tiktok: "TikTok",
        preview: "Alıcı önizlemesi",
        storeRequired: "Önce mağazanızı oluşturun.",
        storeMustBePublic: "Yeni içerik yayınlamak için mağazanızın onaylanmış ve aktif olması gerekir. Mevcut içeriklerinizi yine de kaldırabilirsiniz.",
      }
    : {
        storeStories: "Store Stories",
        storyLoading: "Loading store stories",
        watchStory: "Watch story",
        watchVideo: "Watch video",
        video: "Video",
        watchOnYouTube: "Watch on YouTube",
        watchOnTikTok: "Watch on TikTok",
        visitStore: "Visit store",
        close: "Close",
        previous: "Previous",
        next: "Next",
        storeHighlights: "Store Highlights",
        storeVideos: "Store Videos",
        videosButton: "Videos",
        highlightDescription: "Permanent video showcase from this store.",
        mediaLoading: "Loading store media",
        addMedia: "Add media",
        storeMedia: "Store Media",
        sellerIntro:
          "Paste your public YouTube or TikTok video URL. Shopera turns it into a Store Story or Store Video; Buyers see your store content without platform labels.",
        title: "Title",
        titlePlaceholder: "e.g. Our summer collection",
        videoUrl: "Video URL",
        videoUrlPlaceholder: "Paste a YouTube or TikTok link",
        detected: "Detected",
        invalidVideoUrl: "Paste a valid HTTPS YouTube or TikTok URL.",
        homeStory: "Homepage Story",
        homeStoryHint: "Live for 24 hours · maximum 2 active stories per store",
        storeShowcase: "Store Showcase",
        storeShowcaseHint: "Stays on your Store page until you remove it",
        publish: "Publish",
        publishing: "Publishing...",
        activeStories: "Active homepage stories",
        permanentShowcase: "Permanent Store Showcase",
        noStories: "No active homepage stories yet.",
        noShowcase: "No permanent showcase videos yet.",
        noStoriesPublic: "No live Store Stories right now.",
        noStoriesPublicHint: "Fresh stories from Shopera stores will appear here.",
        noShowcasePublic: "No Store Highlights yet.",
        noShowcasePublicHint: "This store has not added a video yet.",
        storiesUnavailable: "Store Stories are temporarily unavailable.",
        showcaseUnavailable: "Store Highlights are temporarily unavailable.",
        tryAgainLater: "Please try again in a moment.",
        comingSoon: "Coming soon",
        remove: "Remove",
        removeConfirm: "Remove this media from Shopera?",
        yesRemove: "Yes, remove",
        cancel: "Cancel",
        expired: "Expired",
        hoursLeft: "{{hours}}h left",
        minutesLeft: "{{minutes}}m left",
        permanent: "Permanent",
        homeLimit: "2 active story limit",
        loadError: "Store media could not be loaded.",
        publishError: "Media could not be published.",
        removeError: "Media could not be removed.",
        retry: "Retry",
        youtube: "YouTube",
        tiktok: "TikTok",
        preview: "Buyer preview",
        storeRequired: "Create your store first.",
        storeMustBePublic: "Your store must be approved and active before you can publish new content. You can still remove existing media.",
      };
};

export const interpolateStoreMediaCopy = (template, values = {}) =>
  Object.entries(values).reduce(
    (result, [key, value]) => result.replace(`{{${key}}}`, String(value)),
    template
  );
