const defaultNotificationPresentation = {
  icon: "!",
  tone: "default",
  category: "System",
  actionLabel: "View details",
  actionKey: "buyer.notifications.actions.viewDetails",
  categoryKey: "buyer.notifications.categories.system",
  messageKey: null,
  titleKey: null,
};

const notificationPresentationByType = {
  ORDER_PLACED: {
    icon: "O",
    tone: "confirmed",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    titleKey: "buyer.notifications.titles.orderPlaced",
  },
  ORDER_STATUS_CHANGED: {
    icon: "O",
    tone: "processing",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    titleKey: "buyer.notifications.titles.orderUpdated",
  },
  ORDER_CANCELLED: {
    icon: "X",
    tone: "default",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    titleKey: "buyer.notifications.titles.orderCancelled",
  },
  NEW_ORDER: {
    icon: "O",
    tone: "confirmed",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
  },
  StoreApproved: {
    icon: "S",
    tone: "account",
    category: "Account",
    actionLabel: "View details",
    actionKey: "buyer.notifications.actions.viewDetails",
    categoryKey: "buyer.notifications.categories.account",
  },
  StoreRejected: {
    icon: "S",
    tone: "account",
    category: "Account",
    actionLabel: "View details",
    actionKey: "buyer.notifications.actions.viewDetails",
    categoryKey: "buyer.notifications.categories.account",
  },
  AdminMessage: {
    icon: "A",
    tone: "account",
    category: "Account",
    actionLabel: "View details",
    actionKey: "buyer.notifications.actions.viewDetails",
    categoryKey: "buyer.notifications.categories.account",
  },
  OrderConfirmed: {
    icon: "C",
    tone: "confirmed",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    messageKey: "buyer.notifications.messages.orderConfirmed",
    titleKey: "buyer.notifications.titles.orderConfirmed",
  },
  OrderProcessing: {
    icon: "P",
    tone: "processing",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    messageKey: "buyer.notifications.messages.orderProcessing",
    titleKey: "buyer.notifications.titles.orderProcessing",
  },
  OrderShipped: {
    icon: "S",
    tone: "shipped",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    messageKey: "buyer.notifications.messages.orderShipped",
    titleKey: "buyer.notifications.titles.orderShipped",
  },
  OrderDelivered: {
    icon: "D",
    tone: "delivered",
    category: "Order",
    actionLabel: "View order",
    actionKey: "buyer.notifications.actions.viewOrder",
    categoryKey: "buyer.notifications.categories.order",
    messageKey: "buyer.notifications.messages.orderDelivered",
    titleKey: "buyer.notifications.titles.orderDelivered",
  },
  BackInStockReminder: {
    icon: "!",
    tone: "wishlist",
    category: "Wishlist",
    actionLabel: "View product",
    actionKey: "buyer.notifications.actions.viewProduct",
    categoryKey: "buyer.notifications.categories.wishlist",
    messageKey: "buyer.notifications.messages.backInStock",
    titleKey: "buyer.notifications.titles.backInStock",
  },
  CouponExpiring: {
    icon: "%",
    tone: "promotion",
    category: "Promotion",
    actionLabel: "View coupon",
    actionKey: "buyer.notifications.actions.viewCoupon",
    categoryKey: "buyer.notifications.categories.promotion",
    messageKey: "buyer.notifications.messages.couponExpiring",
    titleKey: "buyer.notifications.titles.couponExpiring",
  },
  AccountSecurity: {
    icon: "A",
    tone: "account",
    category: "Account",
    actionLabel: "Review account",
    actionKey: "buyer.notifications.actions.reviewAccount",
    categoryKey: "buyer.notifications.categories.account",
    messageKey: "buyer.notifications.messages.accountSecurity",
    titleKey: "buyer.notifications.titles.accountSecurity",
  },
};

export const getNotificationPresentation = (notificationType) => {
  return {
    ...defaultNotificationPresentation,
    ...(notificationPresentationByType[notificationType] || {}),
  };
};
