/* ============================================================================
   FINAL E-COMMERCE PHYSICAL DATABASE — SQL SERVER
   Consolidated 23-table schema | July 2026
   This is a clean creation script, not an amendment or migration.
   Test in development before use. No cascade deletes are used.
   ============================================================================ */

IF DB_ID(N'ECommerceDB_Final') IS NULL
    CREATE DATABASE ECommerceDB_Final;
GO
USE ECommerceDB_Final;
GO
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
GO

/* ============================== IDENTITY ============================== */
CREATE TABLE dbo.USER_ACCOUNT
(
    UserID INT IDENTITY(1,1) NOT NULL,
    FullName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(30) NULL,
    RegistrationDate DATETIME2(0) NOT NULL CONSTRAINT DF_USER_RegistrationDate DEFAULT SYSUTCDATETIME(),
    Role NVARCHAR(20) NOT NULL,
    AccountStatus NVARCHAR(20) NOT NULL CONSTRAINT DF_USER_Status DEFAULT N'ACTIVE',
    PermissionLevel NVARCHAR(50) NULL,
    CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY CLUSTERED (UserID),
    CONSTRAINT UQ_USER_Email UNIQUE (Email),
    CONSTRAINT UQ_USER_UserID_Role UNIQUE (UserID, Role),
    CONSTRAINT CK_USER_Email CHECK (Email LIKE N'%_@_%._%'),
    CONSTRAINT CK_USER_Role CHECK (Role IN (N'BUYER',N'SELLER',N'ADMIN')),
    CONSTRAINT CK_USER_Status CHECK (AccountStatus IN (N'ACTIVE',N'INACTIVE',N'SUSPENDED')),
    CONSTRAINT CK_USER_AdminPermission CHECK
    (
        (Role=N'ADMIN' AND PermissionLevel IN (N'SUPER_ADMIN',N'MANAGER',N'SUPPORT'))
        OR (Role<>N'ADMIN' AND PermissionLevel IS NULL)
    )
);
GO

/* ============================== SELLER =============================== */
CREATE TABLE dbo.STORE
(
    StoreID INT IDENTITY(1,1) NOT NULL,
    SellerUserID INT NOT NULL,
    SellerRole AS CONVERT(NVARCHAR(20),N'SELLER') PERSISTED,
    StoreName NVARCHAR(150) NOT NULL,
    StoreSlug NVARCHAR(150) NULL,
    StoreDescription NVARCHAR(1000) NULL,
    StoreLogoURL NVARCHAR(1000) NULL,
    StoreBannerURL NVARCHAR(1000) NULL,
    SupportEmail NVARCHAR(255) NULL,
    SupportPhone NVARCHAR(30) NULL,
    ReturnPolicy NVARCHAR(MAX) NULL,
    SupportPolicy NVARCHAR(MAX) NULL,
    ApprovalStatus NVARCHAR(20) NOT NULL CONSTRAINT DF_STORE_Approval DEFAULT N'PENDING',
    ApprovedByAdminUserID INT NULL,
    ApprovedByAdminRole AS CONVERT(NVARCHAR(20),N'ADMIN') PERSISTED,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_STORE_Created DEFAULT SYSUTCDATETIME(),
    UpdatedDate DATETIME2(0) NULL,
    StoreStatus NVARCHAR(20) NOT NULL CONSTRAINT DF_STORE_Status DEFAULT N'ACTIVE',
    CONSTRAINT PK_STORE PRIMARY KEY CLUSTERED (StoreID),
    CONSTRAINT UQ_STORE_Seller UNIQUE (SellerUserID),
    CONSTRAINT UQ_STORE_Name UNIQUE (StoreName),
    CONSTRAINT CK_STORE_SupportEmail CHECK (SupportEmail IS NULL OR SupportEmail LIKE N'%_@_%._%'),
    CONSTRAINT CK_STORE_Approval CHECK (ApprovalStatus IN (N'PENDING',N'APPROVED',N'REJECTED',N'SUSPENDED')),
    CONSTRAINT CK_STORE_Status CHECK (StoreStatus IN (N'ACTIVE',N'INACTIVE',N'SUSPENDED',N'CLOSED')),
    CONSTRAINT CK_STORE_ApprovalActor CHECK
    (
        (ApprovalStatus=N'PENDING' AND ApprovedByAdminUserID IS NULL)
        OR (ApprovalStatus<>N'PENDING' AND ApprovedByAdminUserID IS NOT NULL)
    ),
    CONSTRAINT CK_STORE_Updated CHECK (UpdatedDate IS NULL OR UpdatedDate>=CreatedDate),
    CONSTRAINT FK_STORE_Seller FOREIGN KEY (SellerUserID,SellerRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role),
    CONSTRAINT FK_STORE_Admin FOREIGN KEY (ApprovedByAdminUserID,ApprovedByAdminRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role)
);
GO
CREATE UNIQUE INDEX UX_STORE_Slug_NotNull ON dbo.STORE(StoreSlug) WHERE StoreSlug IS NOT NULL;
GO

CREATE TABLE dbo.STORE_APPROVAL_HISTORY
(
    StoreApprovalHistoryID INT IDENTITY(1,1) NOT NULL,
    StoreID INT NOT NULL,
    OldStatus NVARCHAR(20) NULL,
    NewStatus NVARCHAR(20) NOT NULL,
    ChangedByAdminUserID INT NOT NULL,
    ChangedByAdminRole AS CONVERT(NVARCHAR(20),N'ADMIN') PERSISTED,
    ChangedDate DATETIME2(0) NOT NULL CONSTRAINT DF_STORE_APPROVAL_Changed DEFAULT SYSUTCDATETIME(),
    DecisionNote NVARCHAR(500) NULL,
    CONSTRAINT PK_STORE_APPROVAL_HISTORY PRIMARY KEY CLUSTERED (StoreApprovalHistoryID),
    CONSTRAINT CK_STORE_APPROVAL_Old CHECK (OldStatus IS NULL OR OldStatus IN (N'PENDING',N'APPROVED',N'REJECTED',N'SUSPENDED')),
    CONSTRAINT CK_STORE_APPROVAL_New CHECK (NewStatus IN (N'PENDING',N'APPROVED',N'REJECTED',N'SUSPENDED')),
    CONSTRAINT CK_STORE_APPROVAL_Changed CHECK (OldStatus IS NULL OR OldStatus<>NewStatus),
    CONSTRAINT FK_STORE_APPROVAL_Store FOREIGN KEY (StoreID) REFERENCES dbo.STORE(StoreID),
    CONSTRAINT FK_STORE_APPROVAL_Admin FOREIGN KEY (ChangedByAdminUserID,ChangedByAdminRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role)
);
GO

/* =========================== COMMUNICATION =========================== */
CREATE TABLE dbo.NOTIFICATION
(
    NotificationID INT IDENTITY(1,1) NOT NULL,
    RecipientUserID INT NOT NULL,
    ActorUserID INT NULL,
    NotificationType NVARCHAR(50) NOT NULL,
    Title NVARCHAR(200) NOT NULL,
    Message NVARCHAR(1000) NOT NULL,
    RelatedEntityType NVARCHAR(50) NULL,
    RelatedEntityID INT NULL,
    IsRead BIT NOT NULL CONSTRAINT DF_NOTIFICATION_IsRead DEFAULT 0,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_NOTIFICATION_Created DEFAULT SYSUTCDATETIME(),
    ReadDate DATETIME2(0) NULL,
    CONSTRAINT PK_NOTIFICATION PRIMARY KEY CLUSTERED (NotificationID),
    CONSTRAINT FK_NOTIFICATION_Recipient FOREIGN KEY (RecipientUserID) REFERENCES dbo.USER_ACCOUNT(UserID),
    CONSTRAINT FK_NOTIFICATION_Actor FOREIGN KEY (ActorUserID) REFERENCES dbo.USER_ACCOUNT(UserID),
    CONSTRAINT CK_NOTIFICATION_EntityPair CHECK
    (
        (RelatedEntityType IS NULL AND RelatedEntityID IS NULL)
        OR (RelatedEntityType IS NOT NULL AND RelatedEntityID IS NOT NULL)
    ),
    CONSTRAINT CK_NOTIFICATION_Read CHECK
    (
        (IsRead=0 AND ReadDate IS NULL) OR (IsRead=1 AND ReadDate IS NOT NULL)
    )
);
GO

/* =============================== BUYER =============================== */
CREATE TABLE dbo.BUYER_ADDRESS
(
    AddressID INT IDENTITY(1,1) NOT NULL,
    BuyerUserID INT NOT NULL,
    BuyerRole AS CONVERT(NVARCHAR(20),N'BUYER') PERSISTED,
    AddressLabel NVARCHAR(50) NULL,
    StreetAddress NVARCHAR(255) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    StateProvince NVARCHAR(100) NULL,
    PostalCode NVARCHAR(30) NULL,
    Country NVARCHAR(100) NOT NULL,
    IsDefaultShipping BIT NOT NULL CONSTRAINT DF_ADDRESS_DefaultShipping DEFAULT 0,
    IsDefaultBilling BIT NOT NULL CONSTRAINT DF_ADDRESS_DefaultBilling DEFAULT 0,
    CONSTRAINT PK_BUYER_ADDRESS PRIMARY KEY CLUSTERED (AddressID),
    CONSTRAINT UQ_ADDRESS_Duplicate UNIQUE (BuyerUserID,StreetAddress,City,PostalCode,Country),
    CONSTRAINT FK_ADDRESS_Buyer FOREIGN KEY (BuyerUserID,BuyerRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role)
);
GO
CREATE UNIQUE INDEX UX_ADDRESS_OneDefaultShipping ON dbo.BUYER_ADDRESS(BuyerUserID) WHERE IsDefaultShipping=1;
CREATE UNIQUE INDEX UX_ADDRESS_OneDefaultBilling ON dbo.BUYER_ADDRESS(BuyerUserID) WHERE IsDefaultBilling=1;
GO

/* ============================= CATALOGUE ============================= */
CREATE TABLE dbo.CATEGORY
(
    CategoryID INT IDENTITY(1,1) NOT NULL,
    CategoryName NVARCHAR(150) NOT NULL,
    Description NVARCHAR(1000) NULL,
    ParentCategoryID INT NULL,
    ManagedByAdminUserID INT NOT NULL,
    ManagedByAdminRole AS CONVERT(NVARCHAR(20),N'ADMIN') PERSISTED,
    CONSTRAINT PK_CATEGORY PRIMARY KEY CLUSTERED (CategoryID),
    CONSTRAINT UQ_CATEGORY_ParentName UNIQUE (ParentCategoryID,CategoryName),
    CONSTRAINT CK_CATEGORY_NotSelf CHECK (ParentCategoryID IS NULL OR ParentCategoryID<>CategoryID),
    CONSTRAINT FK_CATEGORY_Parent FOREIGN KEY (ParentCategoryID) REFERENCES dbo.CATEGORY(CategoryID),
    CONSTRAINT FK_CATEGORY_Admin FOREIGN KEY (ManagedByAdminUserID,ManagedByAdminRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role)
);
GO

CREATE TABLE dbo.PRODUCT
(
    ProductID INT IDENTITY(1,1) NOT NULL,
    ProductName NVARCHAR(200) NOT NULL,
    ShortDescription NVARCHAR(500) NULL,
    Description NVARCHAR(MAX) NULL,
    Brand NVARCHAR(100) NULL,
    ModelNumber NVARCHAR(100) NULL,
    ProductCondition NVARCHAR(20) NOT NULL CONSTRAINT DF_PRODUCT_Condition DEFAULT N'NEW',
    ConditionDescription NVARCHAR(500) NULL,
    Status NVARCHAR(20) NOT NULL CONSTRAINT DF_PRODUCT_Status DEFAULT N'DRAFT',
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_PRODUCT_Created DEFAULT SYSUTCDATETIME(),
    StoreID INT NOT NULL,
    CategoryID INT NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY CLUSTERED (ProductID),
    CONSTRAINT CK_PRODUCT_Condition CHECK (ProductCondition IN (N'NEW',N'USED_LIKE_NEW',N'USED_GOOD',N'USED_FAIR',N'REFURBISHED')),
    CONSTRAINT CK_PRODUCT_Status CHECK (Status IN (N'DRAFT',N'ACTIVE',N'INACTIVE',N'OUT_OF_STOCK',N'DELETED')),
    CONSTRAINT FK_PRODUCT_Store FOREIGN KEY (StoreID) REFERENCES dbo.STORE(StoreID),
    CONSTRAINT FK_PRODUCT_Category FOREIGN KEY (CategoryID) REFERENCES dbo.CATEGORY(CategoryID)
);
GO

CREATE TABLE dbo.PRODUCT_INFO
(
    ProductInfoID INT IDENTITY(1,1) NOT NULL,
    ProductID INT NOT NULL,
    ProductDetails NVARCHAR(MAX) NULL,
    Specifications NVARCHAR(MAX) NULL,
    WhatsInTheBox NVARCHAR(MAX) NULL,
    WarrantyInformation NVARCHAR(MAX) NULL,
    ReturnPolicy NVARCHAR(MAX) NULL,
    CareInstructions NVARCHAR(MAX) NULL,
    AdditionalInformation NVARCHAR(MAX) NULL,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_PRODUCT_INFO_Created DEFAULT SYSUTCDATETIME(),
    UpdatedDate DATETIME2(0) NULL,
    CONSTRAINT PK_PRODUCT_INFO PRIMARY KEY CLUSTERED (ProductInfoID),
    CONSTRAINT UQ_PRODUCT_INFO_Product UNIQUE (ProductID),
    CONSTRAINT CK_PRODUCT_INFO_Details CHECK (ProductDetails IS NULL OR (ISJSON(ProductDetails)=1 AND JSON_QUERY(ProductDetails,N'$.items') IS NOT NULL)),
    CONSTRAINT CK_PRODUCT_INFO_Specs CHECK (Specifications IS NULL OR (ISJSON(Specifications)=1 AND JSON_QUERY(Specifications,N'$.groups') IS NOT NULL)),
    CONSTRAINT CK_PRODUCT_INFO_Box CHECK (WhatsInTheBox IS NULL OR (ISJSON(WhatsInTheBox)=1 AND JSON_QUERY(WhatsInTheBox,N'$.items') IS NOT NULL)),
    CONSTRAINT CK_PRODUCT_INFO_Updated CHECK (UpdatedDate IS NULL OR UpdatedDate>=CreatedDate),
    CONSTRAINT FK_PRODUCT_INFO_Product FOREIGN KEY (ProductID) REFERENCES dbo.PRODUCT(ProductID)
);
GO

CREATE TABLE dbo.PRODUCT_IMAGE
(
    ImageID INT IDENTITY(1,1) NOT NULL,
    ProductID INT NOT NULL,
    ImageURL NVARCHAR(1000) NOT NULL,
    AltText NVARCHAR(255) NULL,
    DisplayOrder INT NOT NULL,
    IsPrimary BIT NOT NULL CONSTRAINT DF_PRODUCT_IMAGE_Primary DEFAULT 0,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_PRODUCT_IMAGE_Created DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_PRODUCT_IMAGE PRIMARY KEY CLUSTERED (ImageID),
    CONSTRAINT UQ_PRODUCT_IMAGE_Order UNIQUE (ProductID,DisplayOrder),
    CONSTRAINT CK_PRODUCT_IMAGE_Order CHECK (DisplayOrder>=1),
    CONSTRAINT FK_PRODUCT_IMAGE_Product FOREIGN KEY (ProductID) REFERENCES dbo.PRODUCT(ProductID)
);
GO
CREATE UNIQUE INDEX UX_PRODUCT_IMAGE_OnePrimary ON dbo.PRODUCT_IMAGE(ProductID) WHERE IsPrimary=1;
GO

CREATE TABLE dbo.PRODUCT_VARIANT
(
    VariantID INT IDENTITY(1,1) NOT NULL,
    ProductID INT NOT NULL,
    SKU NVARCHAR(100) NOT NULL,
    VariantName NVARCHAR(150) NULL,
    Size NVARCHAR(50) NULL,
    Color NVARCHAR(50) NULL,
    StorageCapacity NVARCHAR(50) NULL,
    Price DECIMAL(12,2) NOT NULL,
    CostPrice DECIMAL(12,2) NOT NULL,
    StockQuantity INT NOT NULL CONSTRAINT DF_VARIANT_Stock DEFAULT 0,
    Status NVARCHAR(20) NOT NULL CONSTRAINT DF_VARIANT_Status DEFAULT N'ACTIVE',
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_VARIANT_Created DEFAULT SYSUTCDATETIME(),
    RowVersion ROWVERSION NOT NULL,
    CONSTRAINT PK_PRODUCT_VARIANT PRIMARY KEY CLUSTERED (VariantID),
    CONSTRAINT UQ_VARIANT_SKU UNIQUE (SKU),
    CONSTRAINT UQ_VARIANT_Options UNIQUE (ProductID,Size,Color,StorageCapacity),
    CONSTRAINT CK_VARIANT_Price CHECK (Price>=0),
    CONSTRAINT CK_VARIANT_Cost CHECK (CostPrice>=0),
    CONSTRAINT CK_VARIANT_Stock CHECK (StockQuantity>=0),
    CONSTRAINT CK_VARIANT_Status CHECK (Status IN (N'ACTIVE',N'INACTIVE',N'OUT_OF_STOCK',N'DELETED')),
    CONSTRAINT FK_VARIANT_Product FOREIGN KEY (ProductID) REFERENCES dbo.PRODUCT(ProductID)
);
GO

/* ============================== SHOPPING ============================= */
CREATE TABLE dbo.CART
(
    CartID INT IDENTITY(1,1) NOT NULL,
    BuyerUserID INT NOT NULL,
    BuyerRole AS CONVERT(NVARCHAR(20),N'BUYER') PERSISTED,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_CART_Created DEFAULT SYSUTCDATETIME(),
    Status NVARCHAR(20) NOT NULL CONSTRAINT DF_CART_Status DEFAULT N'ACTIVE',
    CONSTRAINT PK_CART PRIMARY KEY CLUSTERED (CartID),
    CONSTRAINT CK_CART_Status CHECK (Status IN (N'ACTIVE',N'CONVERTED',N'ABANDONED')),
    CONSTRAINT FK_CART_Buyer FOREIGN KEY (BuyerUserID,BuyerRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role)
);
GO
CREATE UNIQUE INDEX UX_CART_OneActive ON dbo.CART(BuyerUserID) WHERE Status=N'ACTIVE';
GO

CREATE TABLE dbo.CART_ITEM
(
    CartItemID INT IDENTITY(1,1) NOT NULL,
    CartID INT NOT NULL,
    VariantID INT NOT NULL,
    Quantity INT NOT NULL,
    UnitPriceAtAdd DECIMAL(12,2) NOT NULL,
    AddedDate DATETIME2(0) NOT NULL CONSTRAINT DF_CART_ITEM_Added DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_CART_ITEM PRIMARY KEY CLUSTERED (CartItemID),
    CONSTRAINT UQ_CART_ITEM_Variant UNIQUE (CartID,VariantID),
    CONSTRAINT CK_CART_ITEM_Quantity CHECK (Quantity>0),
    CONSTRAINT CK_CART_ITEM_Price CHECK (UnitPriceAtAdd>=0),
    CONSTRAINT FK_CART_ITEM_Cart FOREIGN KEY (CartID) REFERENCES dbo.CART(CartID),
    CONSTRAINT FK_CART_ITEM_Variant FOREIGN KEY (VariantID) REFERENCES dbo.PRODUCT_VARIANT(VariantID)
);
GO

CREATE TABLE dbo.WISHLIST
(
    WishlistID INT IDENTITY(1,1) NOT NULL,
    BuyerUserID INT NOT NULL,
    BuyerRole AS CONVERT(NVARCHAR(20),N'BUYER') PERSISTED,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_WISHLIST_Created DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_WISHLIST PRIMARY KEY CLUSTERED (WishlistID),
    CONSTRAINT UQ_WISHLIST_Buyer UNIQUE (BuyerUserID),
    CONSTRAINT FK_WISHLIST_Buyer FOREIGN KEY (BuyerUserID,BuyerRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role)
);
GO

CREATE TABLE dbo.WISHLIST_ITEM
(
    WishlistItemID INT IDENTITY(1,1) NOT NULL,
    WishlistID INT NOT NULL,
    VariantID INT NOT NULL,
    AddedDate DATETIME2(0) NOT NULL CONSTRAINT DF_WISHLIST_ITEM_Added DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_WISHLIST_ITEM PRIMARY KEY CLUSTERED (WishlistItemID),
    CONSTRAINT UQ_WISHLIST_ITEM_Variant UNIQUE (WishlistID,VariantID),
    CONSTRAINT FK_WISHLIST_ITEM_Wishlist FOREIGN KEY (WishlistID) REFERENCES dbo.WISHLIST(WishlistID),
    CONSTRAINT FK_WISHLIST_ITEM_Variant FOREIGN KEY (VariantID) REFERENCES dbo.PRODUCT_VARIANT(VariantID)
);
GO

/* =========================== PROMOTION/ORDER ========================= */
CREATE TABLE dbo.COUPON
(
    CouponID INT IDENTITY(1,1) NOT NULL,
    CouponCode NVARCHAR(50) NOT NULL,
    DiscountType NVARCHAR(20) NOT NULL,
    DiscountValue DECIMAL(12,2) NOT NULL,
    ExpiryDate DATETIME2(0) NOT NULL,
    MinPurchaseAmount DECIMAL(12,2) NOT NULL CONSTRAINT DF_COUPON_Min DEFAULT 0,
    UsageLimit INT NULL,
    Status NVARCHAR(20) NOT NULL CONSTRAINT DF_COUPON_Status DEFAULT N'ACTIVE',
    CONSTRAINT PK_COUPON PRIMARY KEY CLUSTERED (CouponID),
    CONSTRAINT UQ_COUPON_Code UNIQUE (CouponCode),
    CONSTRAINT CK_COUPON_Type CHECK (DiscountType IN (N'PERCENTAGE',N'FIXED_AMOUNT')),
    CONSTRAINT CK_COUPON_Value CHECK (DiscountValue>0 AND (DiscountType=N'FIXED_AMOUNT' OR DiscountValue<=100)),
    CONSTRAINT CK_COUPON_Min CHECK (MinPurchaseAmount>=0),
    CONSTRAINT CK_COUPON_Limit CHECK (UsageLimit IS NULL OR UsageLimit>0),
    CONSTRAINT CK_COUPON_Status CHECK (Status IN (N'ACTIVE',N'EXPIRED',N'DISABLED'))
);
GO

CREATE TABLE dbo.CUSTOMER_ORDER
(
    OrderID INT IDENTITY(1,1) NOT NULL,
    OrderNumber NVARCHAR(30) NOT NULL,
    BuyerUserID INT NOT NULL,
    BuyerRole AS CONVERT(NVARCHAR(20),N'BUYER') PERSISTED,
    StoreID INT NOT NULL,
    CouponID INT NULL,
    OrderDate DATETIME2(0) NOT NULL CONSTRAINT DF_ORDER_Date DEFAULT SYSUTCDATETIME(),
    OrderStatus NVARCHAR(20) NOT NULL CONSTRAINT DF_ORDER_Status DEFAULT N'PENDING',
    SubtotalAmount DECIMAL(12,2) NOT NULL,
    DiscountAmount DECIMAL(12,2) NOT NULL CONSTRAINT DF_ORDER_Discount DEFAULT 0,
    ShippingAmount DECIMAL(12,2) NOT NULL CONSTRAINT DF_ORDER_Shipping DEFAULT 0,
    TotalAmount DECIMAL(12,2) NOT NULL,
    CurrencyCode CHAR(3) NOT NULL CONSTRAINT DF_ORDER_Currency DEFAULT 'EUR',
    CONSTRAINT PK_CUSTOMER_ORDER PRIMARY KEY CLUSTERED (OrderID),
    CONSTRAINT UQ_ORDER_Number UNIQUE (OrderNumber),
    CONSTRAINT CK_ORDER_Status CHECK (OrderStatus IN (N'PENDING',N'CONFIRMED',N'PROCESSING',N'SHIPPED',N'DELIVERED',N'CANCELLED',N'RETURNED')),
    CONSTRAINT CK_ORDER_Amounts CHECK
    (
        SubtotalAmount>=0 AND DiscountAmount>=0 AND ShippingAmount>=0 AND TotalAmount>=0
        AND TotalAmount=SubtotalAmount-DiscountAmount+ShippingAmount
    ),
    CONSTRAINT CK_ORDER_Currency CHECK (CurrencyCode=UPPER(CurrencyCode)),
    CONSTRAINT FK_ORDER_Buyer FOREIGN KEY (BuyerUserID,BuyerRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role),
    CONSTRAINT FK_ORDER_Store FOREIGN KEY (StoreID) REFERENCES dbo.STORE(StoreID),
    CONSTRAINT FK_ORDER_Coupon FOREIGN KEY (CouponID) REFERENCES dbo.COUPON(CouponID)
);
GO

CREATE TABLE dbo.ORDER_ADDRESS
(
    OrderAddressID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    AddressType NVARCHAR(20) NOT NULL,
    RecipientName NVARCHAR(150) NOT NULL,
    RecipientPhone NVARCHAR(30) NULL,
    StreetAddress NVARCHAR(255) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    StateProvince NVARCHAR(100) NULL,
    PostalCode NVARCHAR(30) NULL,
    Country NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_ORDER_ADDRESS PRIMARY KEY CLUSTERED (OrderAddressID),
    CONSTRAINT UQ_ORDER_ADDRESS_Type UNIQUE (OrderID,AddressType),
    CONSTRAINT CK_ORDER_ADDRESS_Type CHECK (AddressType IN (N'SHIPPING',N'BILLING')),
    CONSTRAINT FK_ORDER_ADDRESS_Order FOREIGN KEY (OrderID) REFERENCES dbo.CUSTOMER_ORDER(OrderID)
);
GO

CREATE TABLE dbo.ORDER_ITEM
(
    OrderItemID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    VariantID INT NOT NULL,
    ProductNameAtPurchase NVARCHAR(200) NOT NULL,
    SKUAtPurchase NVARCHAR(100) NOT NULL,
    VariantNameAtPurchase NVARCHAR(150) NULL,
    Quantity INT NOT NULL,
    UnitPriceAtPurchase DECIMAL(12,2) NOT NULL,
    UnitCostAtPurchase DECIMAL(12,2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY CLUSTERED (OrderItemID),
    CONSTRAINT UQ_ORDER_ITEM_Variant UNIQUE (OrderID,VariantID),
    CONSTRAINT CK_ORDER_ITEM_Quantity CHECK (Quantity>0),
    CONSTRAINT CK_ORDER_ITEM_Price CHECK (UnitPriceAtPurchase>=0),
    CONSTRAINT CK_ORDER_ITEM_Cost CHECK (UnitCostAtPurchase>=0),
    CONSTRAINT FK_ORDER_ITEM_Order FOREIGN KEY (OrderID) REFERENCES dbo.CUSTOMER_ORDER(OrderID),
    CONSTRAINT FK_ORDER_ITEM_Variant FOREIGN KEY (VariantID) REFERENCES dbo.PRODUCT_VARIANT(VariantID)
);
GO

CREATE TABLE dbo.ORDER_SELLER_FINANCIAL
(
    OrderSellerFinancialID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    GrossSalesAmount DECIMAL(12,2) NOT NULL,
    SellerDiscountAmount DECIMAL(12,2) NOT NULL CONSTRAINT DF_OSF_Discount DEFAULT 0,
    CommissionAmount DECIMAL(12,2) NOT NULL CONSTRAINT DF_OSF_Commission DEFAULT 0,
    RefundAmount DECIMAL(12,2) NOT NULL CONSTRAINT DF_OSF_Refund DEFAULT 0,
    CostOfGoodsAmount DECIMAL(12,2) NOT NULL,
    SellerNetAmount DECIMAL(12,2) NOT NULL,
    EstimatedProfitAmount DECIMAL(12,2) NOT NULL,
    CurrencyCode CHAR(3) NOT NULL,
    CalculatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_OSF_Calculated DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_ORDER_SELLER_FINANCIAL PRIMARY KEY CLUSTERED (OrderSellerFinancialID),
    CONSTRAINT UQ_OSF_Order UNIQUE (OrderID),
    CONSTRAINT CK_OSF_Nonnegative CHECK
    (GrossSalesAmount>=0 AND SellerDiscountAmount>=0 AND CommissionAmount>=0 AND RefundAmount>=0 AND CostOfGoodsAmount>=0),
    CONSTRAINT CK_OSF_Net CHECK (SellerNetAmount=GrossSalesAmount-SellerDiscountAmount-CommissionAmount-RefundAmount),
    CONSTRAINT CK_OSF_Profit CHECK (EstimatedProfitAmount=SellerNetAmount-CostOfGoodsAmount),
    CONSTRAINT CK_OSF_Currency CHECK (CurrencyCode=UPPER(CurrencyCode)),
    CONSTRAINT FK_OSF_Order FOREIGN KEY (OrderID) REFERENCES dbo.CUSTOMER_ORDER(OrderID)
);
GO

CREATE TABLE dbo.PAYMENT
(
    PaymentID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    PaymentDate DATETIME2(0) NULL,
    CreatedDate DATETIME2(0) NOT NULL CONSTRAINT DF_PAYMENT_Created DEFAULT SYSUTCDATETIME(),
    Amount DECIMAL(12,2) NOT NULL,
    PaymentMethod NVARCHAR(30) NOT NULL,
    PaymentStatus NVARCHAR(30) NOT NULL CONSTRAINT DF_PAYMENT_Status DEFAULT N'PENDING',
    TransactionReference NVARCHAR(150) NULL,
    CONSTRAINT PK_PAYMENT PRIMARY KEY CLUSTERED (PaymentID),
    CONSTRAINT CK_PAYMENT_Amount CHECK (Amount>0),
    CONSTRAINT CK_PAYMENT_Method CHECK (PaymentMethod IN (N'CARD',N'CASH_ON_DELIVERY',N'BANK_TRANSFER',N'WALLET')),
    CONSTRAINT CK_PAYMENT_Status CHECK (PaymentStatus IN (N'PENDING',N'AUTHORIZED',N'PAID',N'FAILED',N'REFUNDED',N'PARTIALLY_REFUNDED',N'CANCELLED')),
    CONSTRAINT CK_PAYMENT_Date CHECK
    (
        (PaymentStatus IN (N'PENDING',N'FAILED',N'CANCELLED') AND PaymentDate IS NULL)
        OR (PaymentStatus IN (N'AUTHORIZED',N'PAID',N'REFUNDED',N'PARTIALLY_REFUNDED') AND PaymentDate IS NOT NULL)
    ),
    CONSTRAINT FK_PAYMENT_Order FOREIGN KEY (OrderID) REFERENCES dbo.CUSTOMER_ORDER(OrderID)
);
GO
CREATE UNIQUE INDEX UX_PAYMENT_Reference ON dbo.PAYMENT(TransactionReference) WHERE TransactionReference IS NOT NULL;
CREATE UNIQUE INDEX UX_PAYMENT_OnePaid ON dbo.PAYMENT(OrderID) WHERE PaymentStatus=N'PAID';
GO

CREATE TABLE dbo.SHIPMENT
(
    ShipmentID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    CourierName NVARCHAR(150) NULL,
    TrackingNumber NVARCHAR(150) NULL,
    ShipmentStatus NVARCHAR(30) NOT NULL CONSTRAINT DF_SHIPMENT_Status DEFAULT N'PENDING',
    ShippedDate DATETIME2(0) NULL,
    DeliveredDate DATETIME2(0) NULL,
    ShippingCost DECIMAL(12,2) NOT NULL CONSTRAINT DF_SHIPMENT_Cost DEFAULT 0,
    CONSTRAINT PK_SHIPMENT PRIMARY KEY CLUSTERED (ShipmentID),
    CONSTRAINT CK_SHIPMENT_Status CHECK (ShipmentStatus IN (N'PENDING',N'PACKED',N'SHIPPED',N'IN_TRANSIT',N'DELIVERED',N'RETURNED',N'CANCELLED')),
    CONSTRAINT CK_SHIPMENT_Dates CHECK (DeliveredDate IS NULL OR ShippedDate IS NULL OR DeliveredDate>=ShippedDate),
    CONSTRAINT CK_SHIPMENT_Cost CHECK (ShippingCost>=0),
    CONSTRAINT FK_SHIPMENT_Order FOREIGN KEY (OrderID) REFERENCES dbo.CUSTOMER_ORDER(OrderID)
);
GO
CREATE UNIQUE INDEX UX_SHIPMENT_Tracking ON dbo.SHIPMENT(TrackingNumber) WHERE TrackingNumber IS NOT NULL;
GO

CREATE TABLE dbo.ORDER_STATUS_HISTORY
(
    OrderStatusHistoryID INT IDENTITY(1,1) NOT NULL,
    OrderID INT NOT NULL,
    OldStatus NVARCHAR(20) NULL,
    NewStatus NVARCHAR(20) NOT NULL,
    ChangedDate DATETIME2(0) NOT NULL CONSTRAINT DF_ORDER_HISTORY_Changed DEFAULT SYSUTCDATETIME(),
    ChangedByUserID INT NULL,
    ChangeNote NVARCHAR(500) NULL,
    CONSTRAINT PK_ORDER_STATUS_HISTORY PRIMARY KEY CLUSTERED (OrderStatusHistoryID),
    CONSTRAINT CK_ORDER_HISTORY_Old CHECK (OldStatus IS NULL OR OldStatus IN (N'PENDING',N'CONFIRMED',N'PROCESSING',N'SHIPPED',N'DELIVERED',N'CANCELLED',N'RETURNED')),
    CONSTRAINT CK_ORDER_HISTORY_New CHECK (NewStatus IN (N'PENDING',N'CONFIRMED',N'PROCESSING',N'SHIPPED',N'DELIVERED',N'CANCELLED',N'RETURNED')),
    CONSTRAINT CK_ORDER_HISTORY_Changed CHECK (OldStatus IS NULL OR OldStatus<>NewStatus),
    CONSTRAINT FK_ORDER_HISTORY_Order FOREIGN KEY (OrderID) REFERENCES dbo.CUSTOMER_ORDER(OrderID),
    CONSTRAINT FK_ORDER_HISTORY_User FOREIGN KEY (ChangedByUserID) REFERENCES dbo.USER_ACCOUNT(UserID)
);
GO

/* ============================== ENGAGEMENT =========================== */
CREATE TABLE dbo.REVIEW
(
    ReviewID INT IDENTITY(1,1) NOT NULL,
    BuyerUserID INT NOT NULL,
    BuyerRole AS CONVERT(NVARCHAR(20),N'BUYER') PERSISTED,
    ProductID INT NOT NULL,
    Rating TINYINT NOT NULL,
    Comment NVARCHAR(2000) NULL,
    ReviewDate DATETIME2(0) NOT NULL CONSTRAINT DF_REVIEW_Date DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_REVIEW PRIMARY KEY CLUSTERED (ReviewID),
    CONSTRAINT UQ_REVIEW_BuyerProduct UNIQUE (BuyerUserID,ProductID),
    CONSTRAINT CK_REVIEW_Rating CHECK (Rating BETWEEN 1 AND 5),
    CONSTRAINT FK_REVIEW_Buyer FOREIGN KEY (BuyerUserID,BuyerRole) REFERENCES dbo.USER_ACCOUNT(UserID,Role),
    CONSTRAINT FK_REVIEW_Product FOREIGN KEY (ProductID) REFERENCES dbo.PRODUCT(ProductID)
);
GO

/* ======================== FOREIGN-KEY/QUERY INDEXES ================== */
CREATE INDEX IX_STORE_Admin ON dbo.STORE(ApprovedByAdminUserID);
CREATE INDEX IX_STORE_APPROVAL_StoreDate ON dbo.STORE_APPROVAL_HISTORY(StoreID,ChangedDate DESC);
CREATE INDEX IX_NOTIFICATION_RecipientDate ON dbo.NOTIFICATION(RecipientUserID,CreatedDate DESC);
CREATE INDEX IX_NOTIFICATION_Unread ON dbo.NOTIFICATION(RecipientUserID,IsRead) INCLUDE (CreatedDate,NotificationType);
CREATE INDEX IX_NOTIFICATION_Entity ON dbo.NOTIFICATION(RelatedEntityType,RelatedEntityID) WHERE RelatedEntityType IS NOT NULL;
CREATE INDEX IX_ADDRESS_Buyer ON dbo.BUYER_ADDRESS(BuyerUserID);
CREATE INDEX IX_CATEGORY_Parent ON dbo.CATEGORY(ParentCategoryID);
CREATE INDEX IX_PRODUCT_StoreStatus ON dbo.PRODUCT(StoreID,Status);
CREATE INDEX IX_PRODUCT_CategoryStatus ON dbo.PRODUCT(CategoryID,Status);
CREATE INDEX IX_PRODUCT_IMAGE_Product ON dbo.PRODUCT_IMAGE(ProductID);
CREATE INDEX IX_VARIANT_ProductStatus ON dbo.PRODUCT_VARIANT(ProductID,Status);
CREATE INDEX IX_CART_Buyer ON dbo.CART(BuyerUserID);
CREATE INDEX IX_CART_ITEM_Variant ON dbo.CART_ITEM(VariantID);
CREATE INDEX IX_WISHLIST_ITEM_Variant ON dbo.WISHLIST_ITEM(VariantID);
CREATE INDEX IX_ORDER_BuyerDate ON dbo.CUSTOMER_ORDER(BuyerUserID,OrderDate DESC);
CREATE INDEX IX_ORDER_StoreDate ON dbo.CUSTOMER_ORDER(StoreID,OrderDate DESC);
CREATE INDEX IX_ORDER_Status ON dbo.CUSTOMER_ORDER(OrderStatus);
CREATE INDEX IX_ORDER_Coupon ON dbo.CUSTOMER_ORDER(CouponID);
CREATE INDEX IX_ORDER_ITEM_Variant ON dbo.ORDER_ITEM(VariantID);
CREATE INDEX IX_PAYMENT_Order ON dbo.PAYMENT(OrderID);
CREATE INDEX IX_SHIPMENT_Order ON dbo.SHIPMENT(OrderID);
CREATE INDEX IX_ORDER_HISTORY_OrderDate ON dbo.ORDER_STATUS_HISTORY(OrderID,ChangedDate DESC);
CREATE INDEX IX_REVIEW_Product ON dbo.REVIEW(ProductID);
GO

/* ============================================================================
   APPLICATION TRANSACTION REQUIREMENT
   The backend—not a trigger—must create ORDER_STATUS_HISTORY so the real seller
   or admin actor is preserved. In one transaction it must:
   1) validate authenticated buyer, active one-store cart, variants, address;
   2) calculate totals from database price; 3) create order/item/address snapshots;
   4) reduce stock with RowVersion/atomic concurrency; 5) create seller finance;
   6) create initial history and buyer/seller notifications; 7) convert the cart;
   8) commit only when all steps succeed. Return HTTP 409 on stock conflict.
   ============================================================================ */
